### ISSUE TITLE
CAT with nonexisting path will crash.

### ISSUE THREAD

**Issue by lennart-benschop** [AgonConsole8/agon-mos#48] opened 2024-04-01 09:50 UTC
Discovered in MOS 2.2.1

When you type the following command on the command line:

CAT xyzzy

the system crashes if xyzzy does not happen to be the name of a directory.
If you type a pattern containing stars, it appears to work just right.

**Comment by stevesims** [comment] 2024-04-01 16:05
this bug has now even fixed, with the fix released as part of 2.2.2.

this issue was caused by a mistake in determining whether or not a directory exists.  the method that had been used would work in the emulator, but wouldn't on-device.  a bug report has been filed on the emulator about this inconsistent behaviour

**Closed by stevesims** 2024-04-01 16:05 UTC
